name: Recolector Mercadona Diario

on:
  schedule:
    - cron: '0 2 * * *' # Se ejecuta todos los días a las 02:00 UTC
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub

permissions:
  contents: write

jobs:
  scrape-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Ejecutar Scraper
      run: python scraper.py

    - name: Commit y Push de los nuevos datos
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data/products.json data/history.json
        # Solo hace commit si hay cambios reales
        git diff --quiet && git diff --staged --quiet || (git commit -m "Actualización diaria de precios 🛒" && git push)
